[package]
name    = "toml_formatted"
version = "0.1.0"
edition = "2024"

[dependencies]
toml_formatted_macros = { workspace = true }
toml_formatted_core   = { workspace = true }
toml_edit             = { workspace = true, features = ["serde"] }
